### ISSUE TITLE
Segmentation Fault 11 on macOS Big Sur (Intel)

### ISSUE THREAD

**Issue by brunocastello** [PCemOnMac/PCemV17macOS#24]
I downloaded the last release from here and unfortunately the app does not open, I have placed the roms in the right place, however, the app refuses to open, no warning, no alert, no mention of the reason why. The icon comes on dock and leaves.

macOS Big Sur 11.4, retina Macbook Pro 13" 2013.

**Comment by almeath** [comment]
A while back, I forked v17 while it was still running well on Mojave and Big Sur on my Intel machines. I was concerned that any subsequent changes (either to the code, or from Apple's side) might break it. Can you let me know or this version will run for you? It does not include any changes since 1 March that were made in an attempt to get it running on Apple Silicon. 

https://github.com/almeath/PCemV17macOS

**Comment by brunocastello** [comment]
I'm gonna try it now. Gimme a few minutes...

**Comment by brunocastello** [comment]
Nope, it doesn't run. Same error.

**Comment by almeath** [comment]
Both versions were working for you previously though? Can you pinpoint a time it suddenly failed, i.e after an Apple software update perhaps?

**Comment by brunocastello** [comment]
I can say that I havent tried PCem since last time we talked about. Then I went through two minor maCOS Big Sur updates, 11.3 and 11.4. This weekend and today I tried to run, it didn't work, then I decided to compile all versions available (kyro's v16, v17, yours v17, and sarah's updated v17) and all them are giving me a segfault 11.

**Comment by almeath** [comment]
Ok, that helps. It still works fine in Mojave on my iMac. I will need to do some tests in Big Sur 11.4 on my MacBook.

**Comment by brunocastello** [comment]
Hi, any luck? In case you need, here's my brew list:
![Screen Shot 2021-07-14 at 5 41 00 PM](https://user-images.githubusercontent.com/23453202/125690033-de1e8d40-3b44-4c09-9108-6e3c8c9c222e.png)
Please note that I tried both your preferred wxmac installation method (as described in the instructions) and then later the homebrew newest wxmac and got the same results, a segfault 11. Newest wxmac is mentioned to be working now with pcem in our discussions area here on github, and also provides dark mode to the app now.

Apart of trying different wxmac versions, nothing different; openal-soft and sdl2 are installed as well.

As of now, Following versions are not working on Big Sur 11.4:

yours v16 and v17, kyr0's v16 and v17, Sarah's latest v17 and the oldest, JamesFreeman959's v14 port. Basically all ports I know for mac.

**Comment by brunocastello** [comment]
Apparently the problem lies with the roms for the most powerful & newest machine configurations. I tried everything up from 486 and above and it segfaults. for some roms from 386 and below it works and others don't.

**Comment by brunocastello** [comment]
@almeath I decided to investigate even further and re-read the old thread: https://github.com/PCemOnMac/PCemV14MacOSX/issues/7

I got these files again: Your PCemV16 and wxmac 3.0.5.1 from February 16 https://github.com/PCemOnMac/PCemV14MacOSX/issues/7#issuecomment-779586970

And your PCemV17 from February 16 https://github.com/PCemOnMac/PCemV14MacOSX/issues/7#issuecomment-779611620

I've installed your precompiled wxmac there and dang v16 did boot a machine! But v17 got stuck trying to boot.

I'll try again later after a good nap to compile the v17 from source and also recompile wxmac with the newest version, because I really want to use the dark mode. I have also found the wxmac.rb script in our old thread for that attempt.

**Comment by almeath** [comment]
Good to hear that you are making progress, and happy birthday :)

Yes, it does sound like a compilation issue could be the culprit, so let me know how you go with re-compiling for v17.

**Comment by brunocastello** [comment]
Here we go:

**@almeath 's v16 precompiled + wxmac precompiled = success**
almeath's v17 precompiled + wxmac precompiled = fail

me compiling almeath's v16 and v17's with new wxmac = fail
me compiling kyr0's v16 and 17 with both new and old wxmac = fail
me compiling sarah's v17 with both wxmacs = fail

Clearly I am missing some dependency to build wxmac. I am even following the instructions from the old thread, but cannot seem to be able to build both wxmac and PCem correctly on my end. Hmmm...

**Comment by brunocastello** [comment]
@almeath could this be a part of the problem? Since it runs well on anything before Big Sur.
https://github.com/libsdl-org/SDL-1.2/commit/89fc1b1c8a65d2f642bb05be9cdac2636c82ff5f

**Comment by brunocastello** [comment]
@almeath I think I've found the problem when trying to compile PCem v17 from this repo and Sarah's repo.

Both gave me the same error related to the macOS SDK, something about an include <iostream> from macOS SDK and "isxdigit". Not sure what is this all about. But I am on macOS Big Sur 11.4, and Xcode 12.5.1. Apparently it can compile against an older SDK, but I do not know how to change nor if this is possible. 

Xcode 13 and macOS Monterey are on the horizon this year to be released around september.

**Comment by brunocastello** [comment]
![Screen Shot 2021-07-24 at 5 21 54 PM](https://user-images.githubusercontent.com/23453202/126880292-d6531bdc-bf14-4a85-84df-0103db1c3d90.png)

**Comment by almeath** [comment]
I just tried a fresh compile in Big Sur 11.4 using the instructions on my Github page, and it results in the same issues you have experienced. I can get older BIOS to work, up to the American Megatrends WinBIOS. Anything later is tending to segfault and crash PCem. Clearly, something Apple updated or changed in 11.4 has broken an otherwise functioning v17 build, but only in relation to something the more demanding systems need to function. 

When I tried my custom app bundle, already working perfectly in Mojave, I get an error about "libwx_osx_cocoau_xrc-3.0.0.0.5.0.dylib" not being identified, so Apple considers it "malware" and wont let my app run (typical Apple BS, stopping me from using an app I put together myself). This is basically why I am still on Mojave and do not plan to upgrade my iMac from this point forward. It just does not pay to be on Apple's cutting edge.

**Comment by almeath** [comment]
All I can say at this stage, is I have a functioning self-contained app bundle for PCem v17 running on Big Sur 11.4, and I used dylibbundler to make sure it finds all of its dependencies inside the app bundle. There are no errors when it launches, but I cannot get past the segfaults when more advanced BIOS configurations are selected.

**Comment by almeath** [comment]
While I can deal with compilation errors and getting working builds, I have no deep coding experience to trouble shoot things that leads to crashes and segfaults. We may have to approach the group that is taking over PCem and see if they have any Mac users who can take a deeper look at this with us.

**Comment by dob205** [comment]
So I decided to mess around with the configure.ac in the latest snapshot of the PCem repository and the culprit at the moment is the -O3 optimization flag inside it. Switching to -O1 made it possible to run it, but it makes the Pentium 75 which ran previously at 100% with my MacBook Pro Retina Late 2013 with a built in Intel Core i5-4258U running slower, but it runs just fine on macOS 11.5 (see: screenshot). In theory you could search for the problems inside the code caused by clang in the newest Xcode version.
![image](https://user-images.githubusercontent.com/2078457/127355342-f4c1920b-c2c4-494c-8302-cdb8d326d34e.png)

**Comment by tomnic79** [comment]
I solved in Ventura modifying the two makefile files, one in src subfolder the other in the root of the project, replace it after the normal config command changing these lines:

`CFLAGS = -O3 -fcommon -fno-inline-functions -mtune=native
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -O3 -fcommon -fno-inline-functions -mtune=native`

**Comment by davidmyers9000** [comment]
I had the same issue and @tomnic79 's solution worked for me. Thank you.

I am on an MBP late 2012 running Ventura via Open Core Legacy Patcher. 

A tip for those not familiar with Make - after updating the Makefile's with the above, run 'make clean' first then 'make' to rebuild.

**Comment by almeath** [comment]
> I had the same issue and [@tomnic79](https://github.com/tomnic79) 's solution worked for me. Thank you.
> 
> I am on an MBP late 2012 running Ventura via Open Core Legacy Patcher.
> 
> A tip for those not familiar with Make - after updating the Makefile's with the above, run 'make clean' first then 'make' to rebuild.

@davidmyers9000 , it has been hard for me to maintain this repository as I am not using a Mac anymore. However, I have access to a new machine running Sequoia and will see if I can get these instructions updated. A quick question - when compiling in Ventura, did you need to follow the supplementary instructions to manually install wxmac from source? Or did it compile with the original Mojave/Catalina instructions, along with the modifications mentioned above?
